version: "3.9"
services:
  rabbit:
    image: rabbitmq:3.10-management
    container_name: 'rabbit'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  app:
    container_name: app
    restart: always
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python src/manage.py runserver 0.0.0.0:8000
    # environment:
    #   - DB_NAME=${DB_NAME}
    #   - DB_USER=${DB_USER}
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_HOST=${DB_HOST}
    #   - DB_PORT=${DB_PORT}
    # depends_on:
    #   - db

  celery:
    container_name: 'celery'
    restart: always
    build:
      context: src
      dockerfile: Dockerfile
    command: celery --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbit:5672// -A setup --workdir src  worker -l info -P gevent
    volumes:
      - .:/code
    links:
      - rabbit
    depends_on:
      - rabbit
